import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/employee.dart';
import '../models/payslip.dart';

class PayslipPdfService {
  static Future<Uint8List> build(Payslip payslip, Employee employee) async {
    final doc = pw.Document();
    String currency(double v) => '${v.toStringAsFixed(0)} MAD';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('HCM Pro',
                      style: pw.TextStyle(
                          fontSize: 22, fontWeight: pw.FontWeight.bold)),
                  pw.Text('Payslip — ${payslip.period}',
                      style: pw.TextStyle(fontSize: 14)),
                ],
              ),
              pw.SizedBox(height: 16),
              pw.Divider(),
              pw.SizedBox(height: 12),
              pw.Text('Employee', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('${employee.fullName}  (${employee.id})'),
              pw.Text(employee.position),
              pw.Text(employee.departmentLabel),
              pw.SizedBox(height: 16),
              pw.Text('Earnings', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              _row('Base Salary', currency(payslip.baseSalary)),
              if (payslip.bonus > 0) _row('Bonus', currency(payslip.bonus)),
              if (payslip.overtime > 0) _row('Overtime', currency(payslip.overtime)),
              _row('Transport Allowance', currency(payslip.transportAllowance)),
              _row('Meal Allowance', currency(payslip.mealAllowance)),
              pw.Divider(),
              _row('Gross Total', currency(payslip.grossSalary), bold: true),
              pw.SizedBox(height: 16),
              pw.Text('Deductions', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              _row('Social Security (CNSS)', currency(payslip.socialSecurity)),
              _row('Income Tax (IR)', currency(payslip.incomeTax)),
              if (payslip.otherDeductions > 0)
                _row('Other Deductions', currency(payslip.otherDeductions)),
              pw.Divider(),
              _row('Total Deductions', currency(payslip.totalDeductions), bold: true),
              pw.SizedBox(height: 20),
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('NET SALARY',
                        style: pw.TextStyle(
                            fontSize: 16, fontWeight: pw.FontWeight.bold)),
                    pw.Text(currency(payslip.netSalary),
                        style: pw.TextStyle(
                            fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),
              pw.Text('Generated by HCM Pro — for informational use.',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  static pw.Widget _row(String label, String value, {bool bold = false}) {
    final style = bold
        ? pw.TextStyle(fontWeight: pw.FontWeight.bold)
        : const pw.TextStyle();
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: style),
          pw.Text(value, style: style),
        ],
      ),
    );
  }
}
