// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// PLACEHOLDER VALUES — this file has not been generated yet. Run
// `flutterfire configure` from the project root once a real Firebase
// project exists; it will overwrite this file with real credentials.
// Until then, every value below is fake, Firebase.initializeApp() will
// throw, and AppBackend falls back to the in-memory mock repositories.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to generate real options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-not-configured',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'hcm-pro-not-configured',
    storageBucket: 'hcm-pro-not-configured.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-not-configured',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'hcm-pro-not-configured',
    storageBucket: 'hcm-pro-not-configured.appspot.com',
    iosBundleId: 'com.hcmpro.app',
  );
}
